name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make zip file
        run: |
          mkdir -p typst-sci/figs
          cp -r --parents sample.typ main.typ lib.typ README.md LICENSE sci.csl refs.bib refs.yml .vscode figs typst-sci
          zip -r typst-sci.zip typst-sci
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: typst-sci.zip
          draft: true
          generate_release_notes: true
